import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { ScrollText, Plus, FileText, XCircle, CheckCircle2, Search, Pencil, ArrowUp, ArrowDown, ArrowUpDown, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from "@/components/ui/dialog";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { EmpresaSelector } from "@/components/contabilidad/EmpresaSelector";
import { useSelectedEmpresa } from "@/hooks/use-selected-empresa";

const TIPO_LABEL: Record<string, string> = { ingreso: "Ingreso", egreso: "Salida", diario: "Diario" };

export const Route = createFileRoute("/admin/contabilidad/polizas/")({
  head: () => ({
    meta: [
      { title: "Pólizas — Contabilidad" },
      { name: "description", content: "Pólizas de ingreso, egreso y diario conforme al SAT." },
    ],
  }),
  component: PolizasPage,
});

const mxn = new Intl.NumberFormat("es-MX", { style: "currency", currency: "MXN" });

type Poliza = {
  id: string;
  tipo: "ingreso" | "egreso" | "diario";
  folio: string;
  fecha: string;
  concepto: string;
  estado: "borrador" | "asentada" | "cancelada";
  total_cargos: number;
  total_abonos: number;
  origen: string | null;
  created_at: string;
  updated_at: string;
};

type OrigenClase = "automatica" | "manual" | "modificada";

// Classify a póliza by how it was produced:
//  - manual: created by a user from the UI
//  - automatica: generated by the system (factura, nómina, etc.) and untouched
//  - modificada: generated by the system but later edited by a user
function clasificarOrigen(p: Poliza): OrigenClase {
  if (!p.origen || p.origen === "manual") return "manual";
  if (p.updated_at && p.created_at) {
    const delta = new Date(p.updated_at).getTime() - new Date(p.created_at).getTime();
    if (delta > 2000) return "modificada";
  }
  return "automatica";
}

function PolizasPage() {
  const qc = useQueryClient();
  const navigate = useNavigate();
  const { selected } = useSelectedEmpresa();
  const empresaId = selected?.id;
  const [tipoFiltro, setTipoFiltro] = useState<string>("todos");
  const [origenFiltro, setOrigenFiltro] = useState<string>("todos");
  const [search, setSearch] = useState("");
  const [anioFiltro, setAnioFiltro] = useState<string>("todos");
  const [mesFiltro, setMesFiltro] = useState<string>("todos");
  const [desde, setDesde] = useState<string>("");
  const [hasta, setHasta] = useState<string>("");
  type SortKey = "folio" | "tipo" | "fecha" | "concepto" | "total_cargos" | "total_abonos" | "estado";
  const [sortKey, setSortKey] = useState<SortKey>("fecha");
  const [sortDir, setSortDir] = useState<"asc" | "desc">("desc");

  const { data: polizas = [], isLoading } = useQuery({
    queryKey: ["polizas", empresaId],
    enabled: !!empresaId,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("polizas" as any)
        .select("id, tipo, folio, fecha, concepto, estado, total_cargos, total_abonos, origen, created_at, updated_at")
        .eq("empresa_id", empresaId!)
        .order("fecha", { ascending: false })
        .order("folio", { ascending: false });
      if (error) throw error;
      return (data ?? []) as unknown as Poliza[];
    },
  });

  const aniosDisponibles = useMemo(() => {
    const set = new Set<string>();
    for (const p of polizas) { if (p.fecha) set.add(p.fecha.slice(0, 4)); }
    return Array.from(set).sort((a, b) => b.localeCompare(a));
  }, [polizas]);

  const MESES = ["Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"];

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    const arr = polizas.filter((p) => {
      if (tipoFiltro !== "todos" && p.tipo !== tipoFiltro) return false;
      if (origenFiltro !== "todos" && clasificarOrigen(p) !== origenFiltro) return false;
      if (q && !p.folio.toLowerCase().includes(q) && !p.concepto.toLowerCase().includes(q)) return false;
      if (anioFiltro !== "todos" && p.fecha.slice(0, 4) !== anioFiltro) return false;
      if (mesFiltro !== "todos" && p.fecha.slice(5, 7) !== mesFiltro) return false;
      if (desde && p.fecha < desde) return false;
      if (hasta && p.fecha > hasta) return false;
      return true;
    });
    const dir = sortDir === "asc" ? 1 : -1;
    arr.sort((a, b) => {
      let av: any; let bv: any;
      switch (sortKey) {
        case "total_cargos": av = Number(a.total_cargos); bv = Number(b.total_cargos); break;
        case "total_abonos": av = Number(a.total_abonos); bv = Number(b.total_abonos); break;
        default: av = (a as any)[sortKey] ?? ""; bv = (b as any)[sortKey] ?? "";
      }
      if (av < bv) return -1 * dir;
      if (av > bv) return 1 * dir;
      return 0;
    });
    return arr;
  }, [polizas, tipoFiltro, origenFiltro, search, anioFiltro, mesFiltro, desde, hasta, sortKey, sortDir]);

  function toggleSort(k: SortKey) {
    if (sortKey === k) setSortDir((d) => (d === "asc" ? "desc" : "asc"));
    else { setSortKey(k); setSortDir(k === "fecha" ? "desc" : "asc"); }
  }
  function SortHeader({ k, label, align }: { k: SortKey; label: string; align?: "left" | "right" | "center" }) {
    const a = align ?? "left";
    const Icon = sortKey === k ? (sortDir === "asc" ? ArrowUp : ArrowDown) : ArrowUpDown;
    return (
      <th className={`px-3 py-2 text-${a}`}>
        <button
          onClick={() => toggleSort(k)}
          className={`inline-flex items-center gap-1 hover:text-foreground transition-colors ${sortKey === k ? "text-foreground" : ""}`}
        >
          {label} <Icon className="h-3 w-3" />
        </button>
      </th>
    );
  }
  const hayFiltroFecha = anioFiltro !== "todos" || mesFiltro !== "todos" || !!desde || !!hasta;

  const [nuevoTipo, setNuevoTipo] = useState<"ingreso" | "egreso" | "diario" | null>(null);
  const [nuevaFecha, setNuevaFecha] = useState<string>(() => new Date().toISOString().slice(0, 10));
  const [nuevoConcepto, setNuevoConcepto] = useState<string>("");

  function abrirNueva(tipo: "ingreso" | "egreso" | "diario") {
    setNuevoTipo(tipo);
    setNuevaFecha(new Date().toISOString().slice(0, 10));
    setNuevoConcepto("");
  }

  const crear = useMutation({
    mutationFn: async (payload: { tipo: "ingreso" | "egreso" | "diario"; fecha: string; concepto: string }) => {
      if (!empresaId) throw new Error("Selecciona una empresa");
      const [anioStr, mesStr] = payload.fecha.split("-");
      const anio = Number(anioStr);
      const mes = Number(mesStr);
      const { data: per } = await supabase
        .from("periodos_contables" as any)
        .select("id")
        .eq("empresa_id", empresaId)
        .eq("anio", anio)
        .eq("mes", mes)
        .maybeSingle();
      const { data, error } = await supabase
        .from("polizas" as any)
        .insert({
          empresa_id: empresaId,
          tipo: payload.tipo,
          fecha: payload.fecha,
          concepto: payload.concepto,
          estado: "borrador",
          periodo_id: (per as any)?.id ?? null,
          origen: "manual",
        })
        .select("id")
        .single();
      if (error) throw error;
      return (data as any).id as string;
    },
    onSuccess: (id) => {
      qc.invalidateQueries({ queryKey: ["polizas"] });
      setNuevoTipo(null);
      window.location.href = `/admin/contabilidad/polizas/${id}`;
    },
    onError: (e: Error) => toast.error(e.message),
  });

  return (
    <section className="space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2">
            <ScrollText className="h-6 w-6 text-primary" /> Pólizas
          </h1>
          <p className="text-sm text-muted-foreground">
            Ingreso, egreso y diario. Solo las pólizas asentadas afectan libros y balanza.
          </p>
        </div>
        <EmpresaSelector />
      </div>

      {!empresaId ? (
        <div className="rounded-lg border border-dashed border-border p-10 text-center text-sm text-muted-foreground">
          Elige una empresa.
        </div>
      ) : (
        <>
          <div className="flex flex-wrap items-center gap-2">
            <div className="relative flex-1 min-w-[220px]">
              <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input placeholder="Buscar folio o concepto…" value={search} onChange={(e) => setSearch(e.target.value)} className="pl-8" />
            </div>
            <Select value={origenFiltro} onValueChange={setOrigenFiltro}>
              <SelectTrigger className="w-[160px]"><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="todos">Todos los orígenes</SelectItem>
                <SelectItem value="automatica">Automática</SelectItem>
                <SelectItem value="manual">Manual</SelectItem>
                <SelectItem value="modificada">Modificada</SelectItem>
              </SelectContent>
            </Select>
            <div className="flex gap-1">
              <Button onClick={() => abrirNueva("ingreso")} size="sm"><Plus className="h-4 w-4 mr-1" /> Ingreso</Button>
              <Button onClick={() => abrirNueva("egreso")} size="sm" variant="outline"><Plus className="h-4 w-4 mr-1" /> Salida</Button>
              <Button onClick={() => abrirNueva("diario")} size="sm" variant="outline"><Plus className="h-4 w-4 mr-1" /> Diario</Button>
            </div>
          </div>

          <div className="flex flex-wrap gap-1 border-b border-border">
            {[
              { v: "todos", label: "Todos" },
              { v: "ingreso", label: "Ingreso" },
              { v: "egreso", label: "Salida" },
              { v: "diario", label: "Diario" },
            ].map((t) => {
              const active = tipoFiltro === t.v;
              const count = t.v === "todos" ? polizas.length : polizas.filter((p) => p.tipo === (t.v as any)).length;
              return (
                <button
                  key={t.v}
                  onClick={() => setTipoFiltro(t.v)}
                  className={`px-3 py-1.5 text-sm rounded-t-md border-b-2 -mb-px transition-colors ${
                    active
                      ? "border-primary text-foreground font-medium"
                      : "border-transparent text-muted-foreground hover:text-foreground"
                  }`}
                >
                  {t.label} <span className="ml-1 text-xs text-muted-foreground">({count})</span>
                </button>
              );
            })}
          </div>


          <div className="flex flex-wrap items-center gap-2">
            <Select value={anioFiltro} onValueChange={setAnioFiltro}>
              <SelectTrigger className="w-[120px]"><SelectValue placeholder="Año" /></SelectTrigger>
              <SelectContent>
                <SelectItem value="todos">Todos los años</SelectItem>
                {aniosDisponibles.map((a) => <SelectItem key={a} value={a}>{a}</SelectItem>)}
              </SelectContent>
            </Select>
            <Select value={mesFiltro} onValueChange={setMesFiltro}>
              <SelectTrigger className="w-[140px]"><SelectValue placeholder="Mes" /></SelectTrigger>
              <SelectContent>
                <SelectItem value="todos">Todos los meses</SelectItem>
                {MESES.map((m, i) => <SelectItem key={m} value={String(i + 1).padStart(2, "0")}>{m}</SelectItem>)}
              </SelectContent>
            </Select>
            <div className="flex items-center gap-1">
              <Label htmlFor="f-desde" className="text-xs text-muted-foreground">Desde</Label>
              <Input id="f-desde" type="date" value={desde} onChange={(e) => setDesde(e.target.value)} className="w-[150px] h-9" />
            </div>
            <div className="flex items-center gap-1">
              <Label htmlFor="f-hasta" className="text-xs text-muted-foreground">Hasta</Label>
              <Input id="f-hasta" type="date" value={hasta} onChange={(e) => setHasta(e.target.value)} className="w-[150px] h-9" />
            </div>
            {hayFiltroFecha && (
              <Button variant="ghost" size="sm" onClick={() => { setAnioFiltro("todos"); setMesFiltro("todos"); setDesde(""); setHasta(""); }}>
                <X className="h-3.5 w-3.5 mr-1" /> Limpiar fechas
              </Button>
            )}
            <div className="ml-auto text-xs text-muted-foreground">{filtered.length} de {polizas.length}</div>
          </div>

          <div className="rounded-lg border border-border overflow-hidden">
            <table className="w-full text-sm">
              <thead className="bg-muted/40 text-xs uppercase text-muted-foreground">
                <tr>
                  <SortHeader k="folio" label="Folio" />
                  <SortHeader k="tipo" label="Tipo" />
                  <SortHeader k="fecha" label="Fecha" />
                  <SortHeader k="concepto" label="Concepto" />
                  <SortHeader k="total_cargos" label="Cargos" align="right" />
                  <SortHeader k="total_abonos" label="Abonos" align="right" />
                  <SortHeader k="estado" label="Estado" align="center" />
                  <th className="text-right px-3 py-2 w-16"></th>
                </tr>
              </thead>
              <tbody>
                {isLoading ? (
                  <tr><td colSpan={8} className="px-3 py-6 text-center text-muted-foreground">Cargando…</td></tr>
                ) : filtered.length === 0 ? (
                  <tr><td colSpan={8} className="px-3 py-8 text-center text-muted-foreground">Sin pólizas.</td></tr>
                ) : filtered.map((p) => (
                  <tr
                    key={p.id}
                    className="border-t border-border hover:bg-muted/20 cursor-pointer"
                    onClick={() => navigate({ to: "/admin/contabilidad/polizas/$id", params: { id: p.id } })}
                  >
                    <td className="px-3 py-2" onClick={(e) => e.stopPropagation()}>
                      <Link to="/admin/contabilidad/polizas/$id" params={{ id: p.id }} className="font-mono text-xs text-primary hover:underline">
                        {p.folio}
                      </Link>
                    </td>
                    <td className="px-3 py-2">{TIPO_LABEL[p.tipo] ?? p.tipo}</td>
                    <td className="px-3 py-2 text-xs text-muted-foreground">{p.fecha}</td>
                    <td className="px-3 py-2 truncate max-w-[420px]">{p.concepto || <span className="text-muted-foreground italic">(sin concepto)</span>}</td>
                    <td className="px-3 py-2 text-right font-mono text-xs">{mxn.format(Number(p.total_cargos))}</td>
                    <td className="px-3 py-2 text-right font-mono text-xs">{mxn.format(Number(p.total_abonos))}</td>
                    <td className="px-3 py-2 text-center">
                      <EstadoBadge estado={p.estado} />
                    </td>
                    <td className="px-3 py-2 text-right" onClick={(e) => e.stopPropagation()}>
                      <Link
                        to="/admin/contabilidad/polizas/$id"
                        params={{ id: p.id }}
                        className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-primary"
                        title={p.estado === "borrador" ? "Editar póliza" : "Ver póliza"}
                      >
                        <Pencil className="h-3.5 w-3.5" />
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}

      <Dialog open={nuevoTipo !== null} onOpenChange={(o) => { if (!o) setNuevoTipo(null); }}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Nueva póliza de {nuevoTipo ? TIPO_LABEL[nuevoTipo] : ""}</DialogTitle>
            <DialogDescription>
              Captura los datos básicos. La póliza se creará como borrador y podrás agregar los movimientos a continuación.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-3 py-2">
            <div className="space-y-1.5">
              <Label htmlFor="nueva-fecha">Fecha</Label>
              <Input
                id="nueva-fecha"
                type="date"
                value={nuevaFecha}
                onChange={(e) => setNuevaFecha(e.target.value)}
              />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="nuevo-concepto">Concepto</Label>
              <Textarea
                id="nuevo-concepto"
                value={nuevoConcepto}
                onChange={(e) => setNuevoConcepto(e.target.value)}
                placeholder="Descripción breve de la póliza"
                rows={3}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setNuevoTipo(null)} disabled={crear.isPending}>Cancelar</Button>
            <Button
              onClick={() => {
                if (!nuevoTipo) return;
                if (!nuevaFecha) { toast.error("Fecha requerida"); return; }
                crear.mutate({ tipo: nuevoTipo, fecha: nuevaFecha, concepto: nuevoConcepto.trim() });
              }}
              disabled={crear.isPending}
            >
              {crear.isPending ? "Creando…" : "Crear y continuar"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </section>
  );
}

function EstadoBadge({ estado }: { estado: string }) {
  if (estado === "asentada") return <Badge className="bg-emerald-500/15 text-emerald-600 border-emerald-500/30 gap-1"><CheckCircle2 className="h-3 w-3" /> Asentada</Badge>;
  if (estado === "cancelada") return <Badge className="bg-destructive/15 text-destructive border-destructive/30 gap-1"><XCircle className="h-3 w-3" /> Cancelada</Badge>;
  return <Badge variant="outline" className="gap-1"><FileText className="h-3 w-3" /> Borrador</Badge>;
}
