// @ts-nocheck
import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "es" | "en";

const translations = {
  // Navigation
  navDashboard: { es: "Dashboard", en: "Dashboard" },
  navCalculator: { es: "Calculadora", en: "Calculator" },
  navOrders: { es: "Pedidos", en: "Orders" },
  navClients: { es: "Clientes", en: "Clients" },
  navDirectory: { es: "Facturación", en: "Billing" },
  navProducts: { es: "Productos", en: "Products" },
  navInventory: { es: "Inventario", en: "Inventory" },
  navInventario: { es: "Almacén", en: "Warehouse" },
  navKardex: { es: "Kardex", en: "Kardex" },
  navStock: { es: "Entradas", en: "Entries" },
  navPromos: { es: "Promociones", en: "Promotions" },
  navPartners: { es: "Partners", en: "Partners" },
  navSales: { es: "Ventas", en: "Sales" },
  navPnL: { es: "P&L", en: "Profit & Loss" },
  navVentasReport: { es: "Reporte ADM", en: "ADM Report" },
  navProspects: { es: "Prospectos", en: "Prospects" },
  navLogistics: { es: "Logística", en: "Logistics" },
  navManiobra: { es: "Maniobra", en: "Maneuver" },
  navPurchaseNeeds: { es: "Necesidades de Compra", en: "Purchase Needs" },
  navDamaged: { es: "Dañados", en: "Damaged" },
  navDevoluciones: { es: "Devoluciones", en: "Returns" },
  navCatalogo: { es: "Catálogo", en: "Catalog" },
  navAIChat: { es: "Gandalf", en: "Gandalf" },
  navPortalAdmin: { es: "Portal Clientes", en: "Client Portal" },
  navDocuments: { es: "Documentos", en: "Documents" },
  navTareas: { es: "Tareas", en: "Tasks" },
  navPriceLists: { es: "Listas de Precio", en: "Price Lists" },
  navAdmin: { es: "Admin", en: "Admin" },
  navLabel: { es: "Navegación", en: "Navigation" },

  // Common
  save: { es: "Guardar", en: "Save" },
  cancel: { es: "Cancelar", en: "Cancel" },
  saved: { es: "Guardado", en: "Saved" },
  saveError: { es: "Error al guardar", en: "Error saving" },
  delete: { es: "Eliminar", en: "Delete" },
  deleting: { es: "Eliminando...", en: "Deleting..." },
  edit: { es: "Editar", en: "Edit" },
  update: { es: "Actualizar", en: "Update" },
  actions: { es: "Acciones", en: "Actions" },
  notes: { es: "Notas", en: "Notes" },
  error: { es: "Error", en: "Error" },
  noResults: { es: "Sin resultados", en: "No results" },
  all: { es: "Todos", en: "All" },
  refresh: { es: "Actualizar", en: "Refresh" },
  clean: { es: "Limpiar", en: "Clear" },
  saving: { es: "Guardando...", en: "Saving..." },
  applying: { es: "Aplicando...", en: "Applying..." },
  comingSoon: { es: "Próximamente", en: "Coming soon" },

  // 404
  notFoundTitle: { es: "404", en: "404" },
  notFoundMessage: { es: "Página no encontrada", en: "Page not found" },
  notFoundReturn: { es: "Volver al inicio", en: "Return to Home" },

  // Dashboard
  greeting_morning: { es: "Buenos días", en: "Good morning" },
  greeting_afternoon: { es: "Buenas tardes", en: "Good afternoon" },
  greeting_evening: { es: "Buenas noches", en: "Good evening" },
  kpiOpenOrders: { es: "Pedidos abiertos", en: "Open orders" },
  kpiDueToday: { es: "Entrega hoy", en: "Due today" },
  kpiDueTomorrow: { es: "Entrega mañana", en: "Due tomorrow" },
  kpiStockRisk: { es: "Riesgo de stock", en: "Stock at risk" },
  kpiMonthlySales: { es: "Ventas del mes", en: "Monthly sales" },
  kpiBultos7d: { es: "Bultos 7 días", en: "Units 7 days" },
  openOrders: { es: "Pedidos abiertos", en: "Open orders" },
  noOpenOrders: { es: "No hay pedidos abiertos", en: "No open orders" },
  purchaseNeeds: { es: "Necesidades de compra", en: "Purchase needs" },
  noPurchaseNeeds: { es: "Sin necesidades de compra pendientes", en: "No pending purchase needs" },
  thOrder: { es: "Pedido", en: "Order" },
  thClient: { es: "Cliente", en: "Client" },
  thOrderDate: { es: "Fecha pedido", en: "Order date" },
  thDeliveryDate: { es: "Fecha entrega", en: "Delivery date" },
  thStatus: { es: "Estado", en: "Status" },
  thTotal: { es: "Total", en: "Total" },
  thRisk: { es: "Riesgo", en: "Risk" },
  thClave: { es: "Clave", en: "SKU" },
  thProduct: { es: "Producto", en: "Product" },
  thSupplier: { es: "Proveedor", en: "Supplier" },
  thToBuy: { es: "Por comprar", en: "To buy" },
  thCommitted: { es: "Comprometido", en: "Committed" },
  thIncoming: { es: "En camino", en: "Incoming" },
  thOrderBy: { es: "Pedir antes de", en: "Order by" },

  // Orders page
  ordersTitle: { es: "Pedidos", en: "Orders" },
  ordersSubtitle: { es: "Gestiona tus pedidos de venta", en: "Manage your sales orders" },
  newOrder: { es: "Nuevo Pedido", en: "New Order" },
  searchOrderPlaceholder: { es: "Buscar por cliente o código...", en: "Search by client or code..." },
  allStatuses: { es: "Todos los estados", en: "All statuses" },
  noOrders: { es: "No hay pedidos", en: "No orders" },
  createFirstOrder: { es: "Crear primer pedido", en: "Create first order" },
  thLines: { es: "Líneas", en: "Lines" },
  ordersLoadError: { es: "Error al cargar pedidos", en: "Failed to load orders" },

  // Stock Entries page
  stockTitle: { es: "Entradas de Inventario", en: "Stock Entries" },
  newEntry: { es: "Nueva Entrada", en: "New Entry" },
  filterFrom: { es: "Desde", en: "From" },
  filterTo: { es: "Hasta", en: "To" },
  filterStatus: { es: "Estado", en: "Status" },
  filterSupplier: { es: "Proveedor", en: "Supplier" },
  statusRecibido: { es: "Recibido", en: "Received" },
  statusProgramado: { es: "Programado", en: "Scheduled" },
  selected: { es: "seleccionadas", en: "selected" },
  changeStatus: { es: "Cambiar estado", en: "Change status" },
  changeDate: { es: "Cambiar fecha", en: "Change date" },
  deselect: { es: "Deseleccionar", en: "Deselect" },
  thDate: { es: "Fecha", en: "Date" },
  thBultos: { es: "Bultos", en: "Units" },
  thReference: { es: "Referencia", en: "Reference" },
  noEntriesMatch: { es: "No hay entradas que coincidan con los filtros.", en: "No entries match the filters." },
  productLabel: { es: "Producto", en: "Product" },
  productRequired: { es: "Producto *", en: "Product *" },
  searchProductPlaceholder: { es: "Buscar por clave o nombre...", en: "Search by SKU or name..." },
  noProductsFound: { es: "No se encontraron productos.", en: "No products found." },
  dateLabel: { es: "Fecha *", en: "Date *" },
  bultosLabel: { es: "Bultos *", en: "Units *" },
  statusLabel: { es: "Estado", en: "Status" },
  referenceLabel: { es: "Referencia", en: "Reference" },
  referencePlaceholder: { es: "Ej: APEX-209356", en: "e.g. APEX-209356" },
  supplierLabel: { es: "Proveedor", en: "Supplier" },
  supplierAutoFill: { es: "Auto-llenado del producto", en: "Auto-filled from product" },
  notesLabel: { es: "Notas", en: "Notes" },
  notesPlaceholder: { es: "Notas adicionales...", en: "Additional notes..." },
  editEntry: { es: "Editar Entrada", en: "Edit Entry" },
  newEntryTitle: { es: "Nueva Entrada", en: "New Entry" },
  editEntryDesc: { es: "Modifica los datos de la entrada.", en: "Modify entry data." },
  newEntryDesc: { es: "Registra una nueva entrada de inventario.", en: "Register a new stock entry." },
  manualTab: { es: "Manual", en: "Manual" },
  pasteTab: { es: "Pegar texto", en: "Paste text" },
  pasteLabel: { es: "Pega el texto de tu orden aquí", en: "Paste your order text here" },
  detectEntries: { es: "Detectar entradas", en: "Detect entries" },
  thProductFound: { es: "Producto encontrado", en: "Product found" },
  productNotFound: { es: "Producto no encontrado", en: "Product not found" },
  saveNEntries: { es: "entradas", en: "entries" },
  bulkChangeStatusTitle: { es: "Cambiar estado", en: "Change status" },
  bulkChangeStatusDesc: { es: "Selecciona el nuevo estado para las entradas seleccionadas.", en: "Select the new status for selected entries." },
  bulkChangeTo: { es: "Cambiar a", en: "Change to" },
  bulkChangeDateTitle: { es: "Cambiar fecha", en: "Change date" },
  bulkChangeDateDesc: { es: "Selecciona la nueva fecha para las entradas seleccionadas.", en: "Select the new date for selected entries." },
  applyDate: { es: "Aplicar fecha", en: "Apply date" },
  bulkDeleteTitle: { es: "¿Eliminar", en: "Delete" },
  bulkDeleteSuffix: { es: "entradas?", en: "entries?" },
  bulkDeleteDesc: { es: "Esta acción no se puede deshacer. Las entradas seleccionadas serán eliminadas permanentemente.", en: "This action cannot be undone. Selected entries will be permanently deleted." },
  deleteEntryTitle: { es: "¿Eliminar entrada?", en: "Delete entry?" },
  deleteEntryDesc: { es: "Esta acción no se puede deshacer. La entrada será eliminada permanentemente.", en: "This action cannot be undone. The entry will be permanently deleted." },
  // Stock toasts
  autoUpdated: { es: "Auto-actualizado", en: "Auto-updated" },
  entriesMarkedReceived: { es: "entradas marcadas como Recibidas", en: "entries marked as Received" },
  entryIdNotFound: { es: "ID de entrada no encontrado", en: "Entry ID not found" },
  productAndQtyRequired: { es: "Producto y cantidad son requeridos.", en: "Product and quantity are required." },
  updated: { es: "Actualizado", en: "Updated" },
  entryUpdated: { es: "Entrada actualizada correctamente.", en: "Entry updated successfully." },
  newEntryRegistered: { es: "Nueva entrada registrada.", en: "New entry registered." },
  deleted: { es: "Eliminado", en: "Deleted" },
  entryDeleted: { es: "Entrada eliminada.", en: "Entry deleted." },
  entriesChangedTo: { es: "entradas cambiadas a", en: "entries changed to" },
  dateChangedIn: { es: "Fecha cambiada en", en: "Date changed in" },
  entriesWord: { es: "entradas", en: "entries" },
  entriesDeleted: { es: "entradas eliminadas.", en: "entries deleted." },
  noValidEntries: { es: "No hay entradas válidas para guardar.", en: "No valid entries to save." },
  entriesRegistered: { es: "entradas registradas.", en: "entries registered." },

  // Centrales page
  // Products page
  productsTitle: { es: "Catálogo de Productos", en: "Product Catalog" },
  productsSubtitle: { es: "Gestiona tu catálogo de productos", en: "Manage your product catalog" },
  searchProductsCatalog: { es: "Buscar por clave, nombre o marca...", en: "Search by SKU, name or brand..." },
  allSuppliers: { es: "Todos los proveedores", en: "All suppliers" },
  allBrands: { es: "Todas las marcas", en: "All brands" },
  activeOnly: { es: "Activos", en: "Active" },
  inactiveOnly: { es: "Inactivos", en: "Inactive" },
  thBrand: { es: "Marca", en: "Brand" },
  thWeight: { es: "Peso (KG)", en: "Weight (KG)" },
  thPrice: { es: "Precio c/IVA", en: "Price w/VAT" },
  thCost: { es: "Costo s/IVA", en: "Cost w/o VAT" },
  thMarginNormal: { es: "Margen", en: "Margin" },
  thMarginBonus: { es: "Margen c/bono", en: "Margin w/bonus" },
  thStockAvailable: { es: "Disponible", en: "Available" },
  thStockIncoming: { es: "En camino", en: "Incoming" },
  thStockCommitted: { es: "Comprometido", en: "Committed" },
  thActive: { es: "Activo", en: "Active" },
  editProduct: { es: "Editar Producto", en: "Edit Product" },
  editProductDesc: { es: "Modifica los datos del producto.", en: "Modify product data." },
  productName: { es: "Nombre", en: "Name" },
  productClave: { es: "Clave (SKU)", en: "SKU Code" },
  productBrand: { es: "Marca", en: "Brand" },
  productWeight: { es: "Peso por bolsa (KG)", en: "Weight per bag (KG)" },
  productPrice: { es: "Precio de venta c/IVA", en: "Sale price w/VAT" },
  productActive: { es: "Producto activo", en: "Product active" },
  productUpdated: { es: "Producto actualizado.", en: "Product updated." },
  noProductsInCatalog: { es: "No hay productos que coincidan.", en: "No products match." },
  productsLoadError: { es: "Error al cargar productos", en: "Failed to load products" },
  stockSection: { es: "Stock", en: "Stock" },
  pricingSection: { es: "Precios y Márgenes", en: "Pricing & Margins" },

  // Clients page
  clientsTitle: { es: "Clientes", en: "Clients" },
  clientsSubtitle: { es: "Gestiona tu cartera de clientes", en: "Manage your client portfolio" },
  searchClientsPlaceholder: { es: "Buscar por nombre, empresa, teléfono o RFC...", en: "Search by name, company, phone or RFC..." },
  newClient: { es: "Nuevo Cliente", en: "New Client" },
  editClient: { es: "Editar Cliente", en: "Edit Client" },
  editClientDesc: { es: "Modifica los datos del cliente.", en: "Modify client data." },
  newClientDesc: { es: "Registra un nuevo cliente.", en: "Register a new client." },
  clientName: { es: "Nombre", en: "Name" },
  clientCompany: { es: "Empresa", en: "Company" },
  clientPhone: { es: "Teléfono", en: "Phone" },
  clientAddress: { es: "Dirección", en: "Address" },
  clientCentral: { es: "Central", en: "Central" },
  clientRfc: { es: "RFC", en: "RFC" },
  clientRazonSocial: { es: "Razón Social", en: "Legal Name" },
  clientCurp: { es: "CURP", en: "CURP" },
  clientCodigoPostal: { es: "Código Postal", en: "Zip Code" },
  clientNombreCfdi: { es: "Nombre CFDI", en: "CFDI Name" },
  clientActive: { es: "Cliente activo", en: "Client active" },
  clientUpdated: { es: "Cliente actualizado.", en: "Client updated." },
  clientCreated: { es: "Cliente creado.", en: "Client created." },
  clientDeactivated: { es: "Cliente desactivado.", en: "Client deactivated." },
  noClientsMatch: { es: "No hay clientes que coincidan.", en: "No clients match." },
  clientsLoadError: { es: "Error al cargar clientes", en: "Failed to load clients" },
  confirmDeactivate: { es: "¿Desactivar este cliente?", en: "Deactivate this client?" },
  confirmDeactivateDesc: { es: "El cliente será marcado como inactivo.", en: "The client will be marked as inactive." },
  deactivate: { es: "Desactivar", en: "Deactivate" },

  centralesTitle: { es: "Centrales", en: "Centrales" },
  thName: { es: "Nombre", en: "Name" },
  thCity: { es: "Ciudad", en: "City" },
  thState: { es: "Estado", en: "State" },
  thType: { es: "Tipo", en: "Type" },
  thPetfoodTier: { es: "Nivel Petfood", en: "Petfood Tier" },
  thRating: { es: "Calificación", en: "Rating" },
  filters: { es: "Filtros", en: "Filters" },
  clearFilters: { es: "Limpiar filtros", en: "Clear filters" },
  allStates: { es: "Todos los estados", en: "All states" },
  allTypes: { es: "Todos los tipos", en: "All types" },
  allTiersCentral: { es: "Todos los niveles", en: "All tiers" },
  ratingMin: { es: "Rating mín", en: "Rating min" },
  ratingMax: { es: "Rating máx", en: "Rating max" },
  details: { es: "Detalles", en: "Details" },
  address: { es: "Dirección", en: "Address" },
  sourceUrl: { es: "URL Fuente", en: "Source URL" },
  lastVisited: { es: "Última visita", en: "Last visited" },
  nextAction: { es: "Próxima acción", en: "Next action" },
  openSource: { es: "Abrir fuente", en: "Open source" },
  markContacted: { es: "Marcar como Contactado", en: "Mark as Contacted" },
  markVisited: { es: "Marcar como Visitado", en: "Mark as Visited" },

  // Negotiation Calculator (existing)
  title: { es: "Calculadora de Negociación", en: "Negotiation Calculator" },
  product: { es: "Producto", en: "Product" },
  searchProduct: { es: "Buscar producto…", en: "Search product…" },
  noProduct: { es: "No se encontró producto.", en: "No product found." },
  missingKg: { es: "— Falta kg por saco", en: "— Missing kg per bag" },
  kgPerBag: { es: "KG por bulto", en: "KG per bag" },
  inputMode: { es: "Modo de Entrada", en: "Input Mode" },
  total_kg: { es: "Total KG", en: "Total KG" },
  num_bags: { es: "Número de Bultos", en: "Number of Bags" },
  total_mxn: { es: "Presupuesto Total (MXN)", en: "Total Budget (MXN)" },
  price_per_kg: { es: "Precio por KG", en: "Price per KG" },
  price_per_bag: { es: "Precio por Bulto", en: "Price per Bag" },
  result: { es: "Resultado", en: "Result" },
  category: { es: "Categoría (Nivel)", en: "Category (Tier)" },
  pricePerKg: { es: "Precio por KG", en: "Price per KG" },
  pricePerBag: { es: "Precio por Bulto", en: "Price per Bag" },
  numBags: { es: "Número de Bultos", en: "Number of Bags" },
  deliveredKg: { es: "KG Entregados", en: "KG Delivered" },
  totalNoIva: { es: "Total sin IVA", en: "Total w/o VAT" },
  totalIva: { es: "Total (IVA incluido)", en: "Total (VAT included)" },
  marginNormal: { es: "Margen Normal", en: "Normal Margin" },
  marginBonus: { es: "Margen con Bono 7%", en: "Margin with 7% Bonus" },
  errorProducts: { es: "Error cargando productos", en: "Error loading products" },
  errorConfig: { es: "Error cargando configuración", en: "Error loading config" },
  errorTiers: { es: "Error cargando niveles de precio", en: "Error loading price tiers" },
  priceNoMatch: {
    es: "El precio ingresado no coincide exactamente con ningún nivel. Se seleccionó el más cercano.",
    en: "The entered price doesn't exactly match any tier. The closest one was selected.",
  },
  priceBagNoMatch: {
    es: "El precio por bolsa no coincide exactamente con ningún nivel. Se seleccionó el más cercano.",
    en: "The bag price doesn't exactly match any tier. The closest one was selected.",
  },
  profitIva: { es: "Utilidad con IVA", en: "Profit (VAT incl.)" },
  profitBonus7: { es: "Utilidad con bono 7%", en: "Profit with 7% bonus" },
  calculator: { es: "Calculadora", en: "Calculator" },
  centrales: { es: "Centrales", en: "Centrales" },
  allTiers: { es: "Todos los niveles", en: "All tiers" },
  addToQuote: { es: "Agregar a cotización", en: "Add to quote" },
  quote: { es: "Cotización", en: "Quote" },
  copySummary: { es: "Copiar resumen", en: "Copy summary" },
  clearQuote: { es: "Limpiar cotización", en: "Clear quote" },
  copiedToClipboard: { es: "Copiado al portapapeles", en: "Copied to clipboard" },
  telTier: { es: "Nivel", en: "Tier" },
  telTotalIva: { es: "Total (IVA)", en: "Total (VAT)" },
  telMargin: { es: "Margen", en: "Margin" },
  telProfit: { es: "Utilidad", en: "Profit" },
  tierMayoreo: { es: "Mayoreo", en: "Wholesale" },
  tierMenudeo1: { es: "Menudeo 1", en: "Retail 1" },
  tierMenudeo2: { es: "Menudeo 2", en: "Retail 2" },
  tierMenudeo3: { es: "Menudeo 3", en: "Retail 3" },
  sectionSale: { es: "Venta", en: "Sale" },
  sectionPrice: { es: "Precio", en: "Price" },
  sectionQuantity: { es: "Cantidad", en: "Quantity" },
  sectionProducts: { es: "Productos", en: "Products" },
  waitingParams: { es: "En espera de parámetros.", en: "Waiting for parameters." },
  selectProductHint: { es: "Selecciona un producto para ver resultados en tiempo real.", en: "Select a product to see real-time results." },
  selectProductToEnable: { es: "Selecciona un producto para habilitar esta sección.", en: "Select a product to enable this section." },
  marginWithBonus7: { es: "Margen con bono 7%", en: "Margin with 7% bonus" },
  quoteTotalIva: { es: "Total IVA", en: "Total VAT" },
  quoteProfit: { es: "Utilidad", en: "Profit" },
  quoteTotalNoIva: { es: "Total sin IVA", en: "Total w/o VAT" },
  quoteBlendedMargin: { es: "Margen ponderado", en: "Blended margin" },
  quoteBlendedMarginBonus: { es: "Margen ponderado (bono 7%)", en: "Blended margin (7% bonus)" },
  quoteProfitBonus: { es: "Utilidad (bono 7%)", en: "Profit (7% bonus)" },
  quoteTotalBags: { es: "Bultos totales", en: "Total bags" },
  quoteTotalKg: { es: "KG totales", en: "Total KG" },
  thBags: { es: "Bultos", en: "Bags" },
  thMargin: { es: "Margen", en: "Margin" },
  thActions: { es: "Acciones", en: "Actions" },
  duplicate: { es: "Duplicar", en: "Duplicate" },
  remove: { es: "Eliminar", en: "Remove" },
  clipBags: { es: "bultos", en: "bags" },
  clipTotalIva: { es: "Total IVA", en: "Total VAT" },
  clipProfit: { es: "Utilidad", en: "Profit" },
  clipMargin: { es: "Margen", en: "Margin" },
  clipProfitBonus: { es: "Utilidad (bono 7%)", en: "Profit (7% bonus)" },
  customMarginLabel: { es: "Tier personalizado (margen objetivo %)", en: "Custom tier (target margin %)" },
  useCustomMargin: { es: "Usar margen personalizado", en: "Use custom margin" },
  customMarginActive: { es: "Personalizado activo", en: "Custom active" },
  customMarginPlaceholder: { es: "Ej: 8.7", en: "e.g. 8.7" },
  customMarginError: { es: "Margen debe ser entre 0% y 60%", en: "Margin must be between 0% and 60%" },
  tierPersonalizado: { es: "Personalizado", en: "Custom" },
  downloadQuote: { es: "Descargar cotización", en: "Download quote" },
  pricesIncludeIva: { es: "Precios incluyen IVA", en: "Prices include VAT" },
  summarySection: { es: "Resumen", en: "Summary" },
  moreProducts: { es: "productos más", en: "more products" },
} as const;

type TranslationKey = keyof typeof translations;

type LanguageContextType = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextType | null>(null);

const LS_KEY = "app-lang";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    if (typeof window === "undefined") return "es";
    const stored = window.localStorage.getItem(LS_KEY);
    return stored === "en" || stored === "es" ? stored : "es";
  });
  const setLang = (l: Lang) => {
    setLangState(l);
    try { window.localStorage.setItem(LS_KEY, l); } catch {}
    // Notify the literal-string wrapper so non-React callers re-render
    try {
      window.dispatchEvent(new CustomEvent("app-lang-change", { detail: l }));
    } catch {}
  };
  const t = (key: TranslationKey) => translations[key]?.[lang] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (ctx) return ctx;
  // Fallback: project is Spanish-only, no provider mounted
  const lang: Lang = "es";
  return {
    lang,
    setLang: (_l: Lang) => {},
    t: (key: TranslationKey) => translations[key]?.[lang] ?? key,
  };
}
