/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as ManiobraTokenRouteImport } from './routes/maniobra.$token'
import { Route as EntregaTokenRouteImport } from './routes/entrega.$token'
import { Route as AdminVentasRouteImport } from './routes/admin.ventas'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminUsoApisRouteImport } from './routes/admin.uso-apis'
import { Route as AdminTareasRouteImport } from './routes/admin.tareas'
import { Route as AdminSelfiesRouteImport } from './routes/admin.selfies'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminRepresentantesRouteImport } from './routes/admin.representantes'
import { Route as AdminProspectosRouteImport } from './routes/admin.prospectos'
import { Route as AdminPromosRouteImport } from './routes/admin.promos'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as AdminPortalRouteImport } from './routes/admin.portal'
import { Route as AdminPnlRouteImport } from './routes/admin.pnl'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as AdminNecesidadesRouteImport } from './routes/admin.necesidades'
import { Route as AdminManiobraRouteImport } from './routes/admin.maniobra'
import { Route as AdminLogisticaRouteImport } from './routes/admin.logistica'
import { Route as AdminListasPreciosRouteImport } from './routes/admin.listas-precios'
import { Route as AdminLaboratoriosRouteImport } from './routes/admin.laboratorios'
import { Route as AdminKardexRouteImport } from './routes/admin.kardex'
import { Route as AdminInventarioRouteImport } from './routes/admin.inventario'
import { Route as AdminGandalfRouteImport } from './routes/admin.gandalf'
import { Route as AdminFacturasRouteImport } from './routes/admin.facturas'
import { Route as AdminEstadoApisRouteImport } from './routes/admin.estado-apis'
import { Route as AdminEntradasRouteImport } from './routes/admin.entradas'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminDocumentosRouteImport } from './routes/admin.documentos'
import { Route as AdminDevolucionesRouteImport } from './routes/admin.devoluciones'
import { Route as AdminDanadosRouteImport } from './routes/admin.danados'
import { Route as AdminCuentaRouteImport } from './routes/admin.cuenta'
import { Route as AdminComprasRouteImport } from './routes/admin.compras'
import { Route as AdminComisionesRouteImport } from './routes/admin.comisiones'
import { Route as AdminCobranzaRouteImport } from './routes/admin.cobranza'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCentralesRouteImport } from './routes/admin.centrales'
import { Route as AdminCatalogoRouteImport } from './routes/admin.catalogo'
import { Route as AdminCalculadoraRouteImport } from './routes/admin.calculadora'
import { Route as AdminAlmacenesRouteImport } from './routes/admin.almacenes'
import { Route as AdminAlmacenRouteImport } from './routes/admin.almacen'
import { Route as AdminAdministracionRouteImport } from './routes/admin.administracion'
import { Route as AdminContabilidadIndexRouteImport } from './routes/admin.contabilidad.index'
import { Route as AdminPedidosIdRouteImport } from './routes/admin.pedidos.$id'
import { Route as AdminFacturasIdRouteImport } from './routes/admin.facturas.$id'
import { Route as AdminDevolucionesNewRouteImport } from './routes/admin.devoluciones.new'
import { Route as AdminDevolucionesListaRouteImport } from './routes/admin.devoluciones.lista'
import { Route as AdminDevolucionesIdRouteImport } from './routes/admin.devoluciones.$id'
import { Route as AdminContabilidadPolizasRouteImport } from './routes/admin.contabilidad.polizas'
import { Route as AdminContabilidadDiarioRouteImport } from './routes/admin.contabilidad.diario'
import { Route as AdminContabilidadCuentasRouteImport } from './routes/admin.contabilidad.cuentas'
import { Route as AdminComprasIdRouteImport } from './routes/admin.compras.$id'
import { Route as AdminClientesIdRouteImport } from './routes/admin.clientes.$id'
import { Route as AdminContabilidadPolizasIdRouteImport } from './routes/admin.contabilidad.polizas.$id'
import { Route as AdminClientesIdPreciosRouteImport } from './routes/admin.clientes.$id.precios'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ManiobraTokenRoute = ManiobraTokenRouteImport.update({
  id: '/maniobra/$token',
  path: '/maniobra/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregaTokenRoute = EntregaTokenRouteImport.update({
  id: '/entrega/$token',
  path: '/entrega/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVentasRoute = AdminVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsoApisRoute = AdminUsoApisRouteImport.update({
  id: '/uso-apis',
  path: '/uso-apis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTareasRoute = AdminTareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSelfiesRoute = AdminSelfiesRouteImport.update({
  id: '/selfies',
  path: '/selfies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRepresentantesRoute = AdminRepresentantesRouteImport.update({
  id: '/representantes',
  path: '/representantes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProspectosRoute = AdminProspectosRouteImport.update({
  id: '/prospectos',
  path: '/prospectos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromosRoute = AdminPromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortalRoute = AdminPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPnlRoute = AdminPnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNecesidadesRoute = AdminNecesidadesRouteImport.update({
  id: '/necesidades',
  path: '/necesidades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminManiobraRoute = AdminManiobraRouteImport.update({
  id: '/maniobra',
  path: '/maniobra',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogisticaRoute = AdminLogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListasPreciosRoute = AdminListasPreciosRouteImport.update({
  id: '/listas-precios',
  path: '/listas-precios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaboratoriosRoute = AdminLaboratoriosRouteImport.update({
  id: '/laboratorios',
  path: '/laboratorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKardexRoute = AdminKardexRouteImport.update({
  id: '/kardex',
  path: '/kardex',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventarioRoute = AdminInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGandalfRoute = AdminGandalfRouteImport.update({
  id: '/gandalf',
  path: '/gandalf',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturasRoute = AdminFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstadoApisRoute = AdminEstadoApisRouteImport.update({
  id: '/estado-apis',
  path: '/estado-apis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntradasRoute = AdminEntradasRouteImport.update({
  id: '/entradas',
  path: '/entradas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentosRoute = AdminDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevolucionesRoute = AdminDevolucionesRouteImport.update({
  id: '/devoluciones',
  path: '/devoluciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDanadosRoute = AdminDanadosRouteImport.update({
  id: '/danados',
  path: '/danados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCuentaRoute = AdminCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComprasRoute = AdminComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComisionesRoute = AdminComisionesRouteImport.update({
  id: '/comisiones',
  path: '/comisiones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCobranzaRoute = AdminCobranzaRouteImport.update({
  id: '/cobranza',
  path: '/cobranza',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCentralesRoute = AdminCentralesRouteImport.update({
  id: '/centrales',
  path: '/centrales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogoRoute = AdminCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalculadoraRoute = AdminCalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlmacenesRoute = AdminAlmacenesRouteImport.update({
  id: '/almacenes',
  path: '/almacenes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlmacenRoute = AdminAlmacenRouteImport.update({
  id: '/almacen',
  path: '/almacen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministracionRoute = AdminAdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContabilidadIndexRoute = AdminContabilidadIndexRouteImport.update({
  id: '/contabilidad/',
  path: '/contabilidad/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosIdRoute = AdminPedidosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPedidosRoute,
} as any)
const AdminFacturasIdRoute = AdminFacturasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminFacturasRoute,
} as any)
const AdminDevolucionesNewRoute = AdminDevolucionesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminDevolucionesRoute,
} as any)
const AdminDevolucionesListaRoute = AdminDevolucionesListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => AdminDevolucionesRoute,
} as any)
const AdminDevolucionesIdRoute = AdminDevolucionesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminDevolucionesRoute,
} as any)
const AdminContabilidadPolizasRoute =
  AdminContabilidadPolizasRouteImport.update({
    id: '/contabilidad/polizas',
    path: '/contabilidad/polizas',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContabilidadDiarioRoute = AdminContabilidadDiarioRouteImport.update({
  id: '/contabilidad/diario',
  path: '/contabilidad/diario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContabilidadCuentasRoute =
  AdminContabilidadCuentasRouteImport.update({
    id: '/contabilidad/cuentas',
    path: '/contabilidad/cuentas',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminComprasIdRoute = AdminComprasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminComprasRoute,
} as any)
const AdminClientesIdRoute = AdminClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminClientesRoute,
} as any)
const AdminContabilidadPolizasIdRoute =
  AdminContabilidadPolizasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminContabilidadPolizasRoute,
  } as any)
const AdminClientesIdPreciosRoute = AdminClientesIdPreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => AdminClientesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/administracion': typeof AdminAdministracionRoute
  '/admin/almacen': typeof AdminAlmacenRoute
  '/admin/almacenes': typeof AdminAlmacenesRoute
  '/admin/calculadora': typeof AdminCalculadoraRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/centrales': typeof AdminCentralesRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/cobranza': typeof AdminCobranzaRoute
  '/admin/comisiones': typeof AdminComisionesRoute
  '/admin/compras': typeof AdminComprasRouteWithChildren
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/danados': typeof AdminDanadosRoute
  '/admin/devoluciones': typeof AdminDevolucionesRouteWithChildren
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/entradas': typeof AdminEntradasRoute
  '/admin/estado-apis': typeof AdminEstadoApisRoute
  '/admin/facturas': typeof AdminFacturasRouteWithChildren
  '/admin/gandalf': typeof AdminGandalfRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/kardex': typeof AdminKardexRoute
  '/admin/laboratorios': typeof AdminLaboratoriosRoute
  '/admin/listas-precios': typeof AdminListasPreciosRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/maniobra': typeof AdminManiobraRoute
  '/admin/necesidades': typeof AdminNecesidadesRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/pnl': typeof AdminPnlRoute
  '/admin/portal': typeof AdminPortalRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/prospectos': typeof AdminProspectosRoute
  '/admin/representantes': typeof AdminRepresentantesRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/selfies': typeof AdminSelfiesRoute
  '/admin/tareas': typeof AdminTareasRoute
  '/admin/uso-apis': typeof AdminUsoApisRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/ventas': typeof AdminVentasRoute
  '/entrega/$token': typeof EntregaTokenRoute
  '/maniobra/$token': typeof ManiobraTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRouteWithChildren
  '/admin/compras/$id': typeof AdminComprasIdRoute
  '/admin/contabilidad/cuentas': typeof AdminContabilidadCuentasRoute
  '/admin/contabilidad/diario': typeof AdminContabilidadDiarioRoute
  '/admin/contabilidad/polizas': typeof AdminContabilidadPolizasRouteWithChildren
  '/admin/devoluciones/$id': typeof AdminDevolucionesIdRoute
  '/admin/devoluciones/lista': typeof AdminDevolucionesListaRoute
  '/admin/devoluciones/new': typeof AdminDevolucionesNewRoute
  '/admin/facturas/$id': typeof AdminFacturasIdRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/contabilidad/': typeof AdminContabilidadIndexRoute
  '/admin/clientes/$id/precios': typeof AdminClientesIdPreciosRoute
  '/admin/contabilidad/polizas/$id': typeof AdminContabilidadPolizasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/administracion': typeof AdminAdministracionRoute
  '/admin/almacen': typeof AdminAlmacenRoute
  '/admin/almacenes': typeof AdminAlmacenesRoute
  '/admin/calculadora': typeof AdminCalculadoraRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/centrales': typeof AdminCentralesRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/cobranza': typeof AdminCobranzaRoute
  '/admin/comisiones': typeof AdminComisionesRoute
  '/admin/compras': typeof AdminComprasRouteWithChildren
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/danados': typeof AdminDanadosRoute
  '/admin/devoluciones': typeof AdminDevolucionesRouteWithChildren
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/entradas': typeof AdminEntradasRoute
  '/admin/estado-apis': typeof AdminEstadoApisRoute
  '/admin/facturas': typeof AdminFacturasRouteWithChildren
  '/admin/gandalf': typeof AdminGandalfRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/kardex': typeof AdminKardexRoute
  '/admin/laboratorios': typeof AdminLaboratoriosRoute
  '/admin/listas-precios': typeof AdminListasPreciosRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/maniobra': typeof AdminManiobraRoute
  '/admin/necesidades': typeof AdminNecesidadesRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/pnl': typeof AdminPnlRoute
  '/admin/portal': typeof AdminPortalRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/prospectos': typeof AdminProspectosRoute
  '/admin/representantes': typeof AdminRepresentantesRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/selfies': typeof AdminSelfiesRoute
  '/admin/tareas': typeof AdminTareasRoute
  '/admin/uso-apis': typeof AdminUsoApisRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/ventas': typeof AdminVentasRoute
  '/entrega/$token': typeof EntregaTokenRoute
  '/maniobra/$token': typeof ManiobraTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/admin': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRouteWithChildren
  '/admin/compras/$id': typeof AdminComprasIdRoute
  '/admin/contabilidad/cuentas': typeof AdminContabilidadCuentasRoute
  '/admin/contabilidad/diario': typeof AdminContabilidadDiarioRoute
  '/admin/contabilidad/polizas': typeof AdminContabilidadPolizasRouteWithChildren
  '/admin/devoluciones/$id': typeof AdminDevolucionesIdRoute
  '/admin/devoluciones/lista': typeof AdminDevolucionesListaRoute
  '/admin/devoluciones/new': typeof AdminDevolucionesNewRoute
  '/admin/facturas/$id': typeof AdminFacturasIdRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/contabilidad': typeof AdminContabilidadIndexRoute
  '/admin/clientes/$id/precios': typeof AdminClientesIdPreciosRoute
  '/admin/contabilidad/polizas/$id': typeof AdminContabilidadPolizasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/administracion': typeof AdminAdministracionRoute
  '/admin/almacen': typeof AdminAlmacenRoute
  '/admin/almacenes': typeof AdminAlmacenesRoute
  '/admin/calculadora': typeof AdminCalculadoraRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/centrales': typeof AdminCentralesRoute
  '/admin/clientes': typeof AdminClientesRouteWithChildren
  '/admin/cobranza': typeof AdminCobranzaRoute
  '/admin/comisiones': typeof AdminComisionesRoute
  '/admin/compras': typeof AdminComprasRouteWithChildren
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/danados': typeof AdminDanadosRoute
  '/admin/devoluciones': typeof AdminDevolucionesRouteWithChildren
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/entradas': typeof AdminEntradasRoute
  '/admin/estado-apis': typeof AdminEstadoApisRoute
  '/admin/facturas': typeof AdminFacturasRouteWithChildren
  '/admin/gandalf': typeof AdminGandalfRoute
  '/admin/inventario': typeof AdminInventarioRoute
  '/admin/kardex': typeof AdminKardexRoute
  '/admin/laboratorios': typeof AdminLaboratoriosRoute
  '/admin/listas-precios': typeof AdminListasPreciosRoute
  '/admin/logistica': typeof AdminLogisticaRoute
  '/admin/maniobra': typeof AdminManiobraRoute
  '/admin/necesidades': typeof AdminNecesidadesRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/pedidos': typeof AdminPedidosRouteWithChildren
  '/admin/pnl': typeof AdminPnlRoute
  '/admin/portal': typeof AdminPortalRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/promos': typeof AdminPromosRoute
  '/admin/prospectos': typeof AdminProspectosRoute
  '/admin/representantes': typeof AdminRepresentantesRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/selfies': typeof AdminSelfiesRoute
  '/admin/tareas': typeof AdminTareasRoute
  '/admin/uso-apis': typeof AdminUsoApisRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/ventas': typeof AdminVentasRoute
  '/entrega/$token': typeof EntregaTokenRoute
  '/maniobra/$token': typeof ManiobraTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/clientes/$id': typeof AdminClientesIdRouteWithChildren
  '/admin/compras/$id': typeof AdminComprasIdRoute
  '/admin/contabilidad/cuentas': typeof AdminContabilidadCuentasRoute
  '/admin/contabilidad/diario': typeof AdminContabilidadDiarioRoute
  '/admin/contabilidad/polizas': typeof AdminContabilidadPolizasRouteWithChildren
  '/admin/devoluciones/$id': typeof AdminDevolucionesIdRoute
  '/admin/devoluciones/lista': typeof AdminDevolucionesListaRoute
  '/admin/devoluciones/new': typeof AdminDevolucionesNewRoute
  '/admin/facturas/$id': typeof AdminFacturasIdRoute
  '/admin/pedidos/$id': typeof AdminPedidosIdRoute
  '/admin/contabilidad/': typeof AdminContabilidadIndexRoute
  '/admin/clientes/$id/precios': typeof AdminClientesIdPreciosRoute
  '/admin/contabilidad/polizas/$id': typeof AdminContabilidadPolizasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/administracion'
    | '/admin/almacen'
    | '/admin/almacenes'
    | '/admin/calculadora'
    | '/admin/catalogo'
    | '/admin/centrales'
    | '/admin/clientes'
    | '/admin/cobranza'
    | '/admin/comisiones'
    | '/admin/compras'
    | '/admin/cuenta'
    | '/admin/danados'
    | '/admin/devoluciones'
    | '/admin/documentos'
    | '/admin/empresas'
    | '/admin/entradas'
    | '/admin/estado-apis'
    | '/admin/facturas'
    | '/admin/gandalf'
    | '/admin/inventario'
    | '/admin/kardex'
    | '/admin/laboratorios'
    | '/admin/listas-precios'
    | '/admin/logistica'
    | '/admin/maniobra'
    | '/admin/necesidades'
    | '/admin/onboarding'
    | '/admin/partners'
    | '/admin/pedidos'
    | '/admin/pnl'
    | '/admin/portal'
    | '/admin/productos'
    | '/admin/promos'
    | '/admin/prospectos'
    | '/admin/representantes'
    | '/admin/sales'
    | '/admin/selfies'
    | '/admin/tareas'
    | '/admin/uso-apis'
    | '/admin/usuarios'
    | '/admin/ventas'
    | '/entrega/$token'
    | '/maniobra/$token'
    | '/portal/$token'
    | '/admin/'
    | '/admin/clientes/$id'
    | '/admin/compras/$id'
    | '/admin/contabilidad/cuentas'
    | '/admin/contabilidad/diario'
    | '/admin/contabilidad/polizas'
    | '/admin/devoluciones/$id'
    | '/admin/devoluciones/lista'
    | '/admin/devoluciones/new'
    | '/admin/facturas/$id'
    | '/admin/pedidos/$id'
    | '/admin/contabilidad/'
    | '/admin/clientes/$id/precios'
    | '/admin/contabilidad/polizas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/administracion'
    | '/admin/almacen'
    | '/admin/almacenes'
    | '/admin/calculadora'
    | '/admin/catalogo'
    | '/admin/centrales'
    | '/admin/clientes'
    | '/admin/cobranza'
    | '/admin/comisiones'
    | '/admin/compras'
    | '/admin/cuenta'
    | '/admin/danados'
    | '/admin/devoluciones'
    | '/admin/documentos'
    | '/admin/empresas'
    | '/admin/entradas'
    | '/admin/estado-apis'
    | '/admin/facturas'
    | '/admin/gandalf'
    | '/admin/inventario'
    | '/admin/kardex'
    | '/admin/laboratorios'
    | '/admin/listas-precios'
    | '/admin/logistica'
    | '/admin/maniobra'
    | '/admin/necesidades'
    | '/admin/onboarding'
    | '/admin/partners'
    | '/admin/pedidos'
    | '/admin/pnl'
    | '/admin/portal'
    | '/admin/productos'
    | '/admin/promos'
    | '/admin/prospectos'
    | '/admin/representantes'
    | '/admin/sales'
    | '/admin/selfies'
    | '/admin/tareas'
    | '/admin/uso-apis'
    | '/admin/usuarios'
    | '/admin/ventas'
    | '/entrega/$token'
    | '/maniobra/$token'
    | '/portal/$token'
    | '/admin'
    | '/admin/clientes/$id'
    | '/admin/compras/$id'
    | '/admin/contabilidad/cuentas'
    | '/admin/contabilidad/diario'
    | '/admin/contabilidad/polizas'
    | '/admin/devoluciones/$id'
    | '/admin/devoluciones/lista'
    | '/admin/devoluciones/new'
    | '/admin/facturas/$id'
    | '/admin/pedidos/$id'
    | '/admin/contabilidad'
    | '/admin/clientes/$id/precios'
    | '/admin/contabilidad/polizas/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/administracion'
    | '/admin/almacen'
    | '/admin/almacenes'
    | '/admin/calculadora'
    | '/admin/catalogo'
    | '/admin/centrales'
    | '/admin/clientes'
    | '/admin/cobranza'
    | '/admin/comisiones'
    | '/admin/compras'
    | '/admin/cuenta'
    | '/admin/danados'
    | '/admin/devoluciones'
    | '/admin/documentos'
    | '/admin/empresas'
    | '/admin/entradas'
    | '/admin/estado-apis'
    | '/admin/facturas'
    | '/admin/gandalf'
    | '/admin/inventario'
    | '/admin/kardex'
    | '/admin/laboratorios'
    | '/admin/listas-precios'
    | '/admin/logistica'
    | '/admin/maniobra'
    | '/admin/necesidades'
    | '/admin/onboarding'
    | '/admin/partners'
    | '/admin/pedidos'
    | '/admin/pnl'
    | '/admin/portal'
    | '/admin/productos'
    | '/admin/promos'
    | '/admin/prospectos'
    | '/admin/representantes'
    | '/admin/sales'
    | '/admin/selfies'
    | '/admin/tareas'
    | '/admin/uso-apis'
    | '/admin/usuarios'
    | '/admin/ventas'
    | '/entrega/$token'
    | '/maniobra/$token'
    | '/portal/$token'
    | '/admin/'
    | '/admin/clientes/$id'
    | '/admin/compras/$id'
    | '/admin/contabilidad/cuentas'
    | '/admin/contabilidad/diario'
    | '/admin/contabilidad/polizas'
    | '/admin/devoluciones/$id'
    | '/admin/devoluciones/lista'
    | '/admin/devoluciones/new'
    | '/admin/facturas/$id'
    | '/admin/pedidos/$id'
    | '/admin/contabilidad/'
    | '/admin/clientes/$id/precios'
    | '/admin/contabilidad/polizas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  EntregaTokenRoute: typeof EntregaTokenRoute
  ManiobraTokenRoute: typeof ManiobraTokenRoute
  PortalTokenRoute: typeof PortalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maniobra/$token': {
      id: '/maniobra/$token'
      path: '/maniobra/$token'
      fullPath: '/maniobra/$token'
      preLoaderRoute: typeof ManiobraTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrega/$token': {
      id: '/entrega/$token'
      path: '/entrega/$token'
      fullPath: '/entrega/$token'
      preLoaderRoute: typeof EntregaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ventas': {
      id: '/admin/ventas'
      path: '/ventas'
      fullPath: '/admin/ventas'
      preLoaderRoute: typeof AdminVentasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/uso-apis': {
      id: '/admin/uso-apis'
      path: '/uso-apis'
      fullPath: '/admin/uso-apis'
      preLoaderRoute: typeof AdminUsoApisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tareas': {
      id: '/admin/tareas'
      path: '/tareas'
      fullPath: '/admin/tareas'
      preLoaderRoute: typeof AdminTareasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/selfies': {
      id: '/admin/selfies'
      path: '/selfies'
      fullPath: '/admin/selfies'
      preLoaderRoute: typeof AdminSelfiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/representantes': {
      id: '/admin/representantes'
      path: '/representantes'
      fullPath: '/admin/representantes'
      preLoaderRoute: typeof AdminRepresentantesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prospectos': {
      id: '/admin/prospectos'
      path: '/prospectos'
      fullPath: '/admin/prospectos'
      preLoaderRoute: typeof AdminProspectosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promos': {
      id: '/admin/promos'
      path: '/promos'
      fullPath: '/admin/promos'
      preLoaderRoute: typeof AdminPromosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portal': {
      id: '/admin/portal'
      path: '/portal'
      fullPath: '/admin/portal'
      preLoaderRoute: typeof AdminPortalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pnl': {
      id: '/admin/pnl'
      path: '/pnl'
      fullPath: '/admin/pnl'
      preLoaderRoute: typeof AdminPnlRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/necesidades': {
      id: '/admin/necesidades'
      path: '/necesidades'
      fullPath: '/admin/necesidades'
      preLoaderRoute: typeof AdminNecesidadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maniobra': {
      id: '/admin/maniobra'
      path: '/maniobra'
      fullPath: '/admin/maniobra'
      preLoaderRoute: typeof AdminManiobraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logistica': {
      id: '/admin/logistica'
      path: '/logistica'
      fullPath: '/admin/logistica'
      preLoaderRoute: typeof AdminLogisticaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listas-precios': {
      id: '/admin/listas-precios'
      path: '/listas-precios'
      fullPath: '/admin/listas-precios'
      preLoaderRoute: typeof AdminListasPreciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/laboratorios': {
      id: '/admin/laboratorios'
      path: '/laboratorios'
      fullPath: '/admin/laboratorios'
      preLoaderRoute: typeof AdminLaboratoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kardex': {
      id: '/admin/kardex'
      path: '/kardex'
      fullPath: '/admin/kardex'
      preLoaderRoute: typeof AdminKardexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventario': {
      id: '/admin/inventario'
      path: '/inventario'
      fullPath: '/admin/inventario'
      preLoaderRoute: typeof AdminInventarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gandalf': {
      id: '/admin/gandalf'
      path: '/gandalf'
      fullPath: '/admin/gandalf'
      preLoaderRoute: typeof AdminGandalfRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facturas': {
      id: '/admin/facturas'
      path: '/facturas'
      fullPath: '/admin/facturas'
      preLoaderRoute: typeof AdminFacturasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estado-apis': {
      id: '/admin/estado-apis'
      path: '/estado-apis'
      fullPath: '/admin/estado-apis'
      preLoaderRoute: typeof AdminEstadoApisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entradas': {
      id: '/admin/entradas'
      path: '/entradas'
      fullPath: '/admin/entradas'
      preLoaderRoute: typeof AdminEntradasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documentos': {
      id: '/admin/documentos'
      path: '/documentos'
      fullPath: '/admin/documentos'
      preLoaderRoute: typeof AdminDocumentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devoluciones': {
      id: '/admin/devoluciones'
      path: '/devoluciones'
      fullPath: '/admin/devoluciones'
      preLoaderRoute: typeof AdminDevolucionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/danados': {
      id: '/admin/danados'
      path: '/danados'
      fullPath: '/admin/danados'
      preLoaderRoute: typeof AdminDanadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cuenta': {
      id: '/admin/cuenta'
      path: '/cuenta'
      fullPath: '/admin/cuenta'
      preLoaderRoute: typeof AdminCuentaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/compras': {
      id: '/admin/compras'
      path: '/compras'
      fullPath: '/admin/compras'
      preLoaderRoute: typeof AdminComprasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comisiones': {
      id: '/admin/comisiones'
      path: '/comisiones'
      fullPath: '/admin/comisiones'
      preLoaderRoute: typeof AdminComisionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cobranza': {
      id: '/admin/cobranza'
      path: '/cobranza'
      fullPath: '/admin/cobranza'
      preLoaderRoute: typeof AdminCobranzaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/centrales': {
      id: '/admin/centrales'
      path: '/centrales'
      fullPath: '/admin/centrales'
      preLoaderRoute: typeof AdminCentralesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogo': {
      id: '/admin/catalogo'
      path: '/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AdminCatalogoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calculadora': {
      id: '/admin/calculadora'
      path: '/calculadora'
      fullPath: '/admin/calculadora'
      preLoaderRoute: typeof AdminCalculadoraRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/almacenes': {
      id: '/admin/almacenes'
      path: '/almacenes'
      fullPath: '/admin/almacenes'
      preLoaderRoute: typeof AdminAlmacenesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/almacen': {
      id: '/admin/almacen'
      path: '/almacen'
      fullPath: '/admin/almacen'
      preLoaderRoute: typeof AdminAlmacenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administracion': {
      id: '/admin/administracion'
      path: '/administracion'
      fullPath: '/admin/administracion'
      preLoaderRoute: typeof AdminAdministracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contabilidad/': {
      id: '/admin/contabilidad/'
      path: '/contabilidad'
      fullPath: '/admin/contabilidad/'
      preLoaderRoute: typeof AdminContabilidadIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos/$id': {
      id: '/admin/pedidos/$id'
      path: '/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AdminPedidosIdRouteImport
      parentRoute: typeof AdminPedidosRoute
    }
    '/admin/facturas/$id': {
      id: '/admin/facturas/$id'
      path: '/$id'
      fullPath: '/admin/facturas/$id'
      preLoaderRoute: typeof AdminFacturasIdRouteImport
      parentRoute: typeof AdminFacturasRoute
    }
    '/admin/devoluciones/new': {
      id: '/admin/devoluciones/new'
      path: '/new'
      fullPath: '/admin/devoluciones/new'
      preLoaderRoute: typeof AdminDevolucionesNewRouteImport
      parentRoute: typeof AdminDevolucionesRoute
    }
    '/admin/devoluciones/lista': {
      id: '/admin/devoluciones/lista'
      path: '/lista'
      fullPath: '/admin/devoluciones/lista'
      preLoaderRoute: typeof AdminDevolucionesListaRouteImport
      parentRoute: typeof AdminDevolucionesRoute
    }
    '/admin/devoluciones/$id': {
      id: '/admin/devoluciones/$id'
      path: '/$id'
      fullPath: '/admin/devoluciones/$id'
      preLoaderRoute: typeof AdminDevolucionesIdRouteImport
      parentRoute: typeof AdminDevolucionesRoute
    }
    '/admin/contabilidad/polizas': {
      id: '/admin/contabilidad/polizas'
      path: '/contabilidad/polizas'
      fullPath: '/admin/contabilidad/polizas'
      preLoaderRoute: typeof AdminContabilidadPolizasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contabilidad/diario': {
      id: '/admin/contabilidad/diario'
      path: '/contabilidad/diario'
      fullPath: '/admin/contabilidad/diario'
      preLoaderRoute: typeof AdminContabilidadDiarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contabilidad/cuentas': {
      id: '/admin/contabilidad/cuentas'
      path: '/contabilidad/cuentas'
      fullPath: '/admin/contabilidad/cuentas'
      preLoaderRoute: typeof AdminContabilidadCuentasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/compras/$id': {
      id: '/admin/compras/$id'
      path: '/$id'
      fullPath: '/admin/compras/$id'
      preLoaderRoute: typeof AdminComprasIdRouteImport
      parentRoute: typeof AdminComprasRoute
    }
    '/admin/clientes/$id': {
      id: '/admin/clientes/$id'
      path: '/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AdminClientesIdRouteImport
      parentRoute: typeof AdminClientesRoute
    }
    '/admin/contabilidad/polizas/$id': {
      id: '/admin/contabilidad/polizas/$id'
      path: '/$id'
      fullPath: '/admin/contabilidad/polizas/$id'
      preLoaderRoute: typeof AdminContabilidadPolizasIdRouteImport
      parentRoute: typeof AdminContabilidadPolizasRoute
    }
    '/admin/clientes/$id/precios': {
      id: '/admin/clientes/$id/precios'
      path: '/precios'
      fullPath: '/admin/clientes/$id/precios'
      preLoaderRoute: typeof AdminClientesIdPreciosRouteImport
      parentRoute: typeof AdminClientesIdRoute
    }
  }
}

interface AdminClientesIdRouteChildren {
  AdminClientesIdPreciosRoute: typeof AdminClientesIdPreciosRoute
}

const AdminClientesIdRouteChildren: AdminClientesIdRouteChildren = {
  AdminClientesIdPreciosRoute: AdminClientesIdPreciosRoute,
}

const AdminClientesIdRouteWithChildren = AdminClientesIdRoute._addFileChildren(
  AdminClientesIdRouteChildren,
)

interface AdminClientesRouteChildren {
  AdminClientesIdRoute: typeof AdminClientesIdRouteWithChildren
}

const AdminClientesRouteChildren: AdminClientesRouteChildren = {
  AdminClientesIdRoute: AdminClientesIdRouteWithChildren,
}

const AdminClientesRouteWithChildren = AdminClientesRoute._addFileChildren(
  AdminClientesRouteChildren,
)

interface AdminComprasRouteChildren {
  AdminComprasIdRoute: typeof AdminComprasIdRoute
}

const AdminComprasRouteChildren: AdminComprasRouteChildren = {
  AdminComprasIdRoute: AdminComprasIdRoute,
}

const AdminComprasRouteWithChildren = AdminComprasRoute._addFileChildren(
  AdminComprasRouteChildren,
)

interface AdminDevolucionesRouteChildren {
  AdminDevolucionesIdRoute: typeof AdminDevolucionesIdRoute
  AdminDevolucionesListaRoute: typeof AdminDevolucionesListaRoute
  AdminDevolucionesNewRoute: typeof AdminDevolucionesNewRoute
}

const AdminDevolucionesRouteChildren: AdminDevolucionesRouteChildren = {
  AdminDevolucionesIdRoute: AdminDevolucionesIdRoute,
  AdminDevolucionesListaRoute: AdminDevolucionesListaRoute,
  AdminDevolucionesNewRoute: AdminDevolucionesNewRoute,
}

const AdminDevolucionesRouteWithChildren =
  AdminDevolucionesRoute._addFileChildren(AdminDevolucionesRouteChildren)

interface AdminFacturasRouteChildren {
  AdminFacturasIdRoute: typeof AdminFacturasIdRoute
}

const AdminFacturasRouteChildren: AdminFacturasRouteChildren = {
  AdminFacturasIdRoute: AdminFacturasIdRoute,
}

const AdminFacturasRouteWithChildren = AdminFacturasRoute._addFileChildren(
  AdminFacturasRouteChildren,
)

interface AdminPedidosRouteChildren {
  AdminPedidosIdRoute: typeof AdminPedidosIdRoute
}

const AdminPedidosRouteChildren: AdminPedidosRouteChildren = {
  AdminPedidosIdRoute: AdminPedidosIdRoute,
}

const AdminPedidosRouteWithChildren = AdminPedidosRoute._addFileChildren(
  AdminPedidosRouteChildren,
)

interface AdminContabilidadPolizasRouteChildren {
  AdminContabilidadPolizasIdRoute: typeof AdminContabilidadPolizasIdRoute
}

const AdminContabilidadPolizasRouteChildren: AdminContabilidadPolizasRouteChildren =
  {
    AdminContabilidadPolizasIdRoute: AdminContabilidadPolizasIdRoute,
  }

const AdminContabilidadPolizasRouteWithChildren =
  AdminContabilidadPolizasRoute._addFileChildren(
    AdminContabilidadPolizasRouteChildren,
  )

interface AdminRouteChildren {
  AdminAdministracionRoute: typeof AdminAdministracionRoute
  AdminAlmacenRoute: typeof AdminAlmacenRoute
  AdminAlmacenesRoute: typeof AdminAlmacenesRoute
  AdminCalculadoraRoute: typeof AdminCalculadoraRoute
  AdminCatalogoRoute: typeof AdminCatalogoRoute
  AdminCentralesRoute: typeof AdminCentralesRoute
  AdminClientesRoute: typeof AdminClientesRouteWithChildren
  AdminCobranzaRoute: typeof AdminCobranzaRoute
  AdminComisionesRoute: typeof AdminComisionesRoute
  AdminComprasRoute: typeof AdminComprasRouteWithChildren
  AdminCuentaRoute: typeof AdminCuentaRoute
  AdminDanadosRoute: typeof AdminDanadosRoute
  AdminDevolucionesRoute: typeof AdminDevolucionesRouteWithChildren
  AdminDocumentosRoute: typeof AdminDocumentosRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminEntradasRoute: typeof AdminEntradasRoute
  AdminEstadoApisRoute: typeof AdminEstadoApisRoute
  AdminFacturasRoute: typeof AdminFacturasRouteWithChildren
  AdminGandalfRoute: typeof AdminGandalfRoute
  AdminInventarioRoute: typeof AdminInventarioRoute
  AdminKardexRoute: typeof AdminKardexRoute
  AdminLaboratoriosRoute: typeof AdminLaboratoriosRoute
  AdminListasPreciosRoute: typeof AdminListasPreciosRoute
  AdminLogisticaRoute: typeof AdminLogisticaRoute
  AdminManiobraRoute: typeof AdminManiobraRoute
  AdminNecesidadesRoute: typeof AdminNecesidadesRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminPedidosRoute: typeof AdminPedidosRouteWithChildren
  AdminPnlRoute: typeof AdminPnlRoute
  AdminPortalRoute: typeof AdminPortalRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminPromosRoute: typeof AdminPromosRoute
  AdminProspectosRoute: typeof AdminProspectosRoute
  AdminRepresentantesRoute: typeof AdminRepresentantesRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSelfiesRoute: typeof AdminSelfiesRoute
  AdminTareasRoute: typeof AdminTareasRoute
  AdminUsoApisRoute: typeof AdminUsoApisRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminVentasRoute: typeof AdminVentasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContabilidadCuentasRoute: typeof AdminContabilidadCuentasRoute
  AdminContabilidadDiarioRoute: typeof AdminContabilidadDiarioRoute
  AdminContabilidadPolizasRoute: typeof AdminContabilidadPolizasRouteWithChildren
  AdminContabilidadIndexRoute: typeof AdminContabilidadIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdministracionRoute: AdminAdministracionRoute,
  AdminAlmacenRoute: AdminAlmacenRoute,
  AdminAlmacenesRoute: AdminAlmacenesRoute,
  AdminCalculadoraRoute: AdminCalculadoraRoute,
  AdminCatalogoRoute: AdminCatalogoRoute,
  AdminCentralesRoute: AdminCentralesRoute,
  AdminClientesRoute: AdminClientesRouteWithChildren,
  AdminCobranzaRoute: AdminCobranzaRoute,
  AdminComisionesRoute: AdminComisionesRoute,
  AdminComprasRoute: AdminComprasRouteWithChildren,
  AdminCuentaRoute: AdminCuentaRoute,
  AdminDanadosRoute: AdminDanadosRoute,
  AdminDevolucionesRoute: AdminDevolucionesRouteWithChildren,
  AdminDocumentosRoute: AdminDocumentosRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminEntradasRoute: AdminEntradasRoute,
  AdminEstadoApisRoute: AdminEstadoApisRoute,
  AdminFacturasRoute: AdminFacturasRouteWithChildren,
  AdminGandalfRoute: AdminGandalfRoute,
  AdminInventarioRoute: AdminInventarioRoute,
  AdminKardexRoute: AdminKardexRoute,
  AdminLaboratoriosRoute: AdminLaboratoriosRoute,
  AdminListasPreciosRoute: AdminListasPreciosRoute,
  AdminLogisticaRoute: AdminLogisticaRoute,
  AdminManiobraRoute: AdminManiobraRoute,
  AdminNecesidadesRoute: AdminNecesidadesRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminPedidosRoute: AdminPedidosRouteWithChildren,
  AdminPnlRoute: AdminPnlRoute,
  AdminPortalRoute: AdminPortalRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminPromosRoute: AdminPromosRoute,
  AdminProspectosRoute: AdminProspectosRoute,
  AdminRepresentantesRoute: AdminRepresentantesRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSelfiesRoute: AdminSelfiesRoute,
  AdminTareasRoute: AdminTareasRoute,
  AdminUsoApisRoute: AdminUsoApisRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminVentasRoute: AdminVentasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContabilidadCuentasRoute: AdminContabilidadCuentasRoute,
  AdminContabilidadDiarioRoute: AdminContabilidadDiarioRoute,
  AdminContabilidadPolizasRoute: AdminContabilidadPolizasRouteWithChildren,
  AdminContabilidadIndexRoute: AdminContabilidadIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  EntregaTokenRoute: EntregaTokenRoute,
  ManiobraTokenRoute: ManiobraTokenRoute,
  PortalTokenRoute: PortalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
