CREATE OR REPLACE VIEW public.clients
WITH (security_invoker = on) AS
SELECT c.id,
    c.razon_social,
    c.razon_social AS name,
    c.nombre_comercial AS nickname,
    c.company,
    c.central,
    c.curp,
    c.codigo_postal,
    c.nombre_cfdi,
    c.contact,
    COALESCE(c.phone, c.telefono) AS phone,
    c.email,
    c.direccion AS address,
    c.lat,
    c.lng,
    c.google_place_id,
    c.rfc,
    c.client_type,
    c.payment_method,
    c.active,
    c.cfdi_pdf_path,
    c.notas AS notes,
    c.delivery_window_from,
    c.delivery_window_until,
    c.delivery_notes,
    c.price_list_id,
    c.payment_terms,
    c.credit_limit,
    c.token_portal,
    c.portal_activo,
    c.created_at,
    c.updated_at,
    c.representante_id,
    c.required_documents,
    c.parent_cliente_id,
    p.razon_social AS parent_name
   FROM public.clientes c
   LEFT JOIN public.clientes p ON p.id = c.parent_cliente_id;