// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghduukttnasuidwzsiiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoZHV1a3R0bmFzdWlkd3pzaWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2NzAzODgsImV4cCI6MjA5NTI0NjM4OH0.nBpAPd5wFra1VC01Bmf3xO7Nn8GjLQbgg5WBTqozsFg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});